<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Offres et quotas bloquants.
 *
 * Une organisation sans plan retombe sur app.plan_par_defaut. Les trois offres
 * creees ici sont un point de depart modifiable : une limite a NULL est
 * illimitee.
 *
 * Les organisations existantes sont rattachees a l'offre illimitee, pour qu'une
 * mise en place des quotas ne bloque personne du jour au lendemain.
 */
final class Version20261007104913 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Offres (plan) et rattachement des organisations.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE plan (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              code VARCHAR(40) NOT NULL,
              libelle VARCHAR(120) NOT NULL,
              limite_evenements_actifs INT DEFAULT NULL,
              limite_billets_par_mois INT DEFAULT NULL,
              limite_membres INT DEFAULT NULL,
              actif BOOLEAN NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DD5A5B7D77153098 ON plan (code)');
        $this->addSql('ALTER TABLE organisation ADD plan_id INT DEFAULT NULL');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              organisation
            ADD
              CONSTRAINT FK_E6E132B4E899029B FOREIGN KEY (plan_id) REFERENCES plan (id)
        SQL);
        $this->addSql('CREATE INDEX IDX_E6E132B4E899029B ON organisation (plan_id)');

        // ---------------------------------------------------------------
        // Offres de depart. limite NULL = illimite.
        // ---------------------------------------------------------------
        $this->addSql(<<<'SQL'
            INSERT INTO plan
              (code, libelle, limite_evenements_actifs, limite_billets_par_mois, limite_membres, actif, created_at)
            VALUES
              ('DECOUVERTE', 'Decouverte', 1, 100, 2, true, NOW()),
              ('PRO', 'Professionnel', 10, 5000, 10, true, NOW()),
              ('ILLIMITE', 'Illimite', NULL, NULL, NULL, true, NOW())
        SQL);

        // Les organisations deja en place passent sur l'offre illimitee :
        // introduire des quotas ne doit bloquer aucun vendeur existant.
        $this->addSql(<<<'SQL'
            UPDATE organisation
            SET plan_id = (SELECT id FROM plan WHERE code = 'ILLIMITE')
            WHERE plan_id IS NULL
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE plan');
        $this->addSql('ALTER TABLE organisation DROP CONSTRAINT FK_E6E132B4E899029B');
        $this->addSql('DROP INDEX IDX_E6E132B4E899029B');
        $this->addSql('ALTER TABLE organisation DROP plan_id');
    }
}
