<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Introduit l'organisation comme tenant de premier rang.
 *
 * Avant : le vendeur etait une ligne « utilisateur » portant le role
 * ORGANISATEUR. Un seul membre par vendeur, un seul taux de commission pour
 * toute la plateforme, et un cloisonnement laisse a la charge de chaque
 * requete.
 *
 * Apres : une organisation porte ses membres (avec leur role), son taux de
 * commission, et sa colonne organisation_id sur les tables cloisonnees. Le
 * filtre Doctrine « tenant » s'appuie sur cette colonne.
 *
 * La reprise des donnees existantes est faite ici : une organisation est creee
 * pour chaque utilisateur deja designe comme organisateur d'un evenement, puis
 * les colonnes sont renseignees avant d'etre passees en NOT NULL.
 */
final class Version20261007091704 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Organisation (tenant) : membres, taux de commission, cloisonnement des donnees.';
    }

    public function up(Schema $schema): void
    {
        // ---------------------------------------------------------------
        // 1. Tables du tenant
        // ---------------------------------------------------------------
        $this->addSql(<<<'SQL'
            CREATE TABLE organisation (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              nom VARCHAR(180) NOT NULL,
              slug VARCHAR(180) NOT NULL,
              actif BOOLEAN NOT NULL,
              taux_commission NUMERIC(5, 4) DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E6E132B4989D9B62 ON organisation (slug)');

        $this->addSql(<<<'SQL'
            CREATE TABLE membre_organisation (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              role VARCHAR(20) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              organisation_id INT NOT NULL,
              utilisateur_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_4F4EAAC59E6B1585 ON membre_organisation (organisation_id)');
        $this->addSql('CREATE INDEX IDX_4F4EAAC5FB88E14F ON membre_organisation (utilisateur_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_membre_organisation ON membre_organisation (organisation_id, utilisateur_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE membre_organisation
            ADD CONSTRAINT FK_4F4EAAC59E6B1585 FOREIGN KEY (organisation_id)
            REFERENCES organisation (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE membre_organisation
            ADD CONSTRAINT FK_4F4EAAC5FB88E14F FOREIGN KEY (utilisateur_id)
            REFERENCES utilisateur (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);

        // ---------------------------------------------------------------
        // 2. Colonnes de cloisonnement, d'abord nullables pour la reprise
        // ---------------------------------------------------------------
        foreach (['evenement', 'billet', 'commande_ligne', 'ticket_design'] as $table) {
            $this->addSql(sprintf('ALTER TABLE %s ADD organisation_id INT DEFAULT NULL', $table));
        }

        // ---------------------------------------------------------------
        // 3. Reprise des donnees existantes
        // ---------------------------------------------------------------
        // Une organisation par utilisateur deja organisateur d'un evenement.
        // On part de evenement.organisateur_id et non du role, pour couvrir les
        // cas ou le role aurait derive.
        $this->addSql(<<<'SQL'
            INSERT INTO organisation (nom, slug, actif, taux_commission, created_at)
            SELECT
              COALESCE(NULLIF(TRIM(u.nom), ''), u.email),
              'organisation-' || u.id,
              u.actif,
              NULL,
              NOW()
            FROM utilisateur u
            WHERE u.id IN (SELECT DISTINCT organisateur_id FROM evenement WHERE organisateur_id IS NOT NULL)
        SQL);

        // L'organisateur devient proprietaire de son organisation.
        $this->addSql(<<<'SQL'
            INSERT INTO membre_organisation (role, created_at, organisation_id, utilisateur_id)
            SELECT 'PROPRIETAIRE', NOW(), o.id, CAST(SUBSTRING(o.slug FROM 14) AS INT)
            FROM organisation o
            WHERE o.slug LIKE 'organisation-%'
        SQL);

        // Rattachement des evenements, puis des tables qui en derivent.
        $this->addSql(<<<'SQL'
            UPDATE evenement e
            SET organisation_id = m.organisation_id
            FROM membre_organisation m
            WHERE m.utilisateur_id = e.organisateur_id
              AND m.role = 'PROPRIETAIRE'
        SQL);
        $this->addSql(<<<'SQL'
            UPDATE billet b
            SET organisation_id = e.organisation_id
            FROM evenement e
            WHERE e.id = b.evenement_id
        SQL);
        $this->addSql(<<<'SQL'
            UPDATE commande_ligne cl
            SET organisation_id = e.organisation_id
            FROM evenement e
            WHERE e.id = cl.evenement_id
        SQL);
        $this->addSql(<<<'SQL'
            UPDATE ticket_design td
            SET organisation_id = e.organisation_id
            FROM evenement e
            WHERE e.id = td.evenement_id
        SQL);

        // ---------------------------------------------------------------
        // 4. Verrouillage : NOT NULL, cles etrangeres, index
        // ---------------------------------------------------------------
        $contraintes = [
            'evenement' => ['IDX_B26681E9E6B1585', 'FK_B26681E9E6B1585'],
            'billet' => ['IDX_1F034AF69E6B1585', 'FK_1F034AF69E6B1585'],
            'commande_ligne' => ['IDX_6E9804409E6B1585', 'FK_6E9804409E6B1585'],
            'ticket_design' => ['IDX_B70D30FB9E6B1585', 'FK_B70D30FB9E6B1585'],
        ];

        foreach ($contraintes as $table => [$index, $cle]) {
            $this->addSql(sprintf('ALTER TABLE %s ALTER COLUMN organisation_id SET NOT NULL', $table));
            $this->addSql(sprintf(
                'ALTER TABLE %s ADD CONSTRAINT %s FOREIGN KEY (organisation_id) REFERENCES organisation (id) NOT DEFERRABLE',
                $table,
                $cle
            ));
            $this->addSql(sprintf('CREATE INDEX %s ON %s (organisation_id)', $index, $table));
        }
    }

    public function down(Schema $schema): void
    {
        $contraintes = [
            'evenement' => ['IDX_B26681E9E6B1585', 'FK_B26681E9E6B1585'],
            'billet' => ['IDX_1F034AF69E6B1585', 'FK_1F034AF69E6B1585'],
            'commande_ligne' => ['IDX_6E9804409E6B1585', 'FK_6E9804409E6B1585'],
            'ticket_design' => ['IDX_B70D30FB9E6B1585', 'FK_B70D30FB9E6B1585'],
        ];

        foreach ($contraintes as $table => [$index, $cle]) {
            $this->addSql(sprintf('ALTER TABLE %s DROP CONSTRAINT %s', $table, $cle));
            $this->addSql(sprintf('DROP INDEX %s', $index));
            $this->addSql(sprintf('ALTER TABLE %s DROP organisation_id', $table));
        }

        $this->addSql('ALTER TABLE membre_organisation DROP CONSTRAINT FK_4F4EAAC59E6B1585');
        $this->addSql('ALTER TABLE membre_organisation DROP CONSTRAINT FK_4F4EAAC5FB88E14F');
        $this->addSql('DROP TABLE membre_organisation');
        $this->addSql('DROP TABLE organisation');
    }
}
