<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Baseline du schema PostgreSQL.
 *
 * Reference unique du schema, generee depuis le mapping des entites. Remplace
 * les 25 migrations d'origine, ecrites en dialecte SQLite.
 *
 * La table des comptes s'appelle « utilisateur » : « user » est un mot reserve
 * PostgreSQL que Doctrine echappe en DDL mais pas en DML.
 */
final class Version20261007091335 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Baseline du schema PostgreSQL (8 entites + transport Messenger).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE app_setting (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              setting_key VARCHAR(100) NOT NULL,
              setting_value VARCHAR(255) NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_app_setting_key ON app_setting (setting_key)');
        $this->addSql(<<<'SQL'
            CREATE TABLE billet (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              qr_code VARCHAR(120) NOT NULL,
              type VARCHAR(20) NOT NULL,
              prix NUMERIC(10, 2) NOT NULL,
              is_valide BOOLEAN NOT NULL,
              is_utilise BOOLEAN NOT NULL,
              date_utilisation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              transaction_id VARCHAR(255) DEFAULT NULL,
              statut_paiement VARCHAR(50) NOT NULL,
              rendered_png_path VARCHAR(500) DEFAULT NULL,
              evenement_id INT NOT NULL,
              client_id INT NOT NULL,
              organisateur_id INT DEFAULT NULL,
              valide_par_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1F034AF67D8B1FB5 ON billet (qr_code)');
        $this->addSql('CREATE INDEX IDX_1F034AF6FD02F13 ON billet (evenement_id)');
        $this->addSql('CREATE INDEX IDX_1F034AF619EB6921 ON billet (client_id)');
        $this->addSql('CREATE INDEX IDX_1F034AF6D936B2FA ON billet (organisateur_id)');
        $this->addSql('CREATE INDEX IDX_1F034AF66AF12ED9 ON billet (valide_par_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE commande (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              reference VARCHAR(32) NOT NULL,
              montant_total NUMERIC(12, 2) NOT NULL,
              numero_client VARCHAR(20) NOT NULL,
              checkout_email VARCHAR(180) DEFAULT NULL,
              access_token VARCHAR(64) DEFAULT NULL,
              statut VARCHAR(50) NOT NULL,
              date_expiration TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              methode_paiement VARCHAR(20) NOT NULL,
              commission_plateforme NUMERIC(12, 2) NOT NULL,
              montant_net_organisateur NUMERIC(12, 2) NOT NULL,
              date_validation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              tentative_validation INT NOT NULL,
              deposit_id VARCHAR(255) DEFAULT NULL,
              reference_transaction_client VARCHAR(64) DEFAULT NULL,
              capture_preuve_paiement VARCHAR(255) DEFAULT NULL,
              client_id INT DEFAULT NULL,
              valide_par_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6EEAA67DAEA34913 ON commande (reference)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6EEAA67D9815E4B1 ON commande (deposit_id)');
        $this->addSql('CREATE INDEX IDX_6EEAA67D19EB6921 ON commande (client_id)');
        $this->addSql('CREATE INDEX IDX_6EEAA67D6AF12ED9 ON commande (valide_par_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE commande_ligne (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              quantite INT NOT NULL,
              prix_unitaire NUMERIC(10, 2) NOT NULL,
              type_billet VARCHAR(10) NOT NULL,
              commande_id INT NOT NULL,
              evenement_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_6E98044082EA2E54 ON commande_ligne (commande_id)');
        $this->addSql('CREATE INDEX IDX_6E980440FD02F13 ON commande_ligne (evenement_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE evenement (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              nom VARCHAR(255) NOT NULL,
              description TEXT NOT NULL,
              slug VARCHAR(255) NOT NULL,
              date_evenement TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              lieu VARCHAR(255) NOT NULL,
              adresse VARCHAR(255) NOT NULL,
              ville VARCHAR(100) NOT NULL,
              places_disponibles INT NOT NULL,
              places_vendues INT NOT NULL,
              prix_simple NUMERIC(10, 2) NOT NULL,
              prix_vip NUMERIC(10, 2) DEFAULT NULL,
              affiche_principale VARCHAR(500) DEFAULT NULL,
              autres_affiches JSON DEFAULT NULL,
              categorie VARCHAR(50) DEFAULT 'autre' NOT NULL,
              is_active BOOLEAN NOT NULL,
              is_valide BOOLEAN NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              organisateur_paye BOOLEAN NOT NULL,
              organisateur_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_B26681ED936B2FA ON evenement (organisateur_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE log_securite (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              action VARCHAR(50) NOT NULL,
              reference_commande VARCHAR(255) DEFAULT NULL,
              details TEXT DEFAULT NULL,
              ip_address VARCHAR(45) DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              utilisateur_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_BFC94251FB88E14F ON log_securite (utilisateur_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE ticket_design (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              type_billet VARCHAR(10) NOT NULL,
              design_path VARCHAR(500) NOT NULL,
              design_width INT NOT NULL,
              design_height INT NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              evenement_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_B70D30FBFD02F13 ON ticket_design (evenement_id)');
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uniq_ticket_design_evenement_type ON ticket_design (evenement_id, type_billet)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE utilisateur (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              email VARCHAR(180) NOT NULL,
              roles JSON NOT NULL,
              password VARCHAR(255) NOT NULL,
              nom VARCHAR(255) NOT NULL,
              telephone VARCHAR(20) DEFAULT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              is_verified BOOLEAN NOT NULL,
              verification_token VARCHAR(100) DEFAULT NULL,
              role VARCHAR(20) NOT NULL,
              actif BOOLEAN NOT NULL,
              balance INT NOT NULL,
              checkout_account BOOLEAN NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1D1C63B3E7927C74 ON utilisateur (email)');
        $this->addSql(<<<'SQL'
            CREATE TABLE messenger_messages (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              body TEXT NOT NULL,
              headers TEXT NOT NULL,
              queue_name VARCHAR(190) NOT NULL,
              created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (
              queue_name, available_at, delivered_at,
              id
            )
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              billet
            ADD
              CONSTRAINT FK_1F034AF6FD02F13 FOREIGN KEY (evenement_id) REFERENCES evenement (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              billet
            ADD
              CONSTRAINT FK_1F034AF619EB6921 FOREIGN KEY (client_id) REFERENCES utilisateur (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              billet
            ADD
              CONSTRAINT FK_1F034AF6D936B2FA FOREIGN KEY (organisateur_id) REFERENCES utilisateur (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              billet
            ADD
              CONSTRAINT FK_1F034AF66AF12ED9 FOREIGN KEY (valide_par_id) REFERENCES utilisateur (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              commande
            ADD
              CONSTRAINT FK_6EEAA67D19EB6921 FOREIGN KEY (client_id) REFERENCES utilisateur (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              commande
            ADD
              CONSTRAINT FK_6EEAA67D6AF12ED9 FOREIGN KEY (valide_par_id) REFERENCES utilisateur (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              commande_ligne
            ADD
              CONSTRAINT FK_6E98044082EA2E54 FOREIGN KEY (commande_id) REFERENCES commande (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              commande_ligne
            ADD
              CONSTRAINT FK_6E980440FD02F13 FOREIGN KEY (evenement_id) REFERENCES evenement (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              evenement
            ADD
              CONSTRAINT FK_B26681ED936B2FA FOREIGN KEY (organisateur_id) REFERENCES utilisateur (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              log_securite
            ADD
              CONSTRAINT FK_BFC94251FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              ticket_design
            ADD
              CONSTRAINT FK_B70D30FBFD02F13 FOREIGN KEY (evenement_id) REFERENCES evenement (id) NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE billet DROP CONSTRAINT FK_1F034AF6FD02F13');
        $this->addSql('ALTER TABLE billet DROP CONSTRAINT FK_1F034AF619EB6921');
        $this->addSql('ALTER TABLE billet DROP CONSTRAINT FK_1F034AF6D936B2FA');
        $this->addSql('ALTER TABLE billet DROP CONSTRAINT FK_1F034AF66AF12ED9');
        $this->addSql('ALTER TABLE commande DROP CONSTRAINT FK_6EEAA67D19EB6921');
        $this->addSql('ALTER TABLE commande DROP CONSTRAINT FK_6EEAA67D6AF12ED9');
        $this->addSql('ALTER TABLE commande_ligne DROP CONSTRAINT FK_6E98044082EA2E54');
        $this->addSql('ALTER TABLE commande_ligne DROP CONSTRAINT FK_6E980440FD02F13');
        $this->addSql('ALTER TABLE evenement DROP CONSTRAINT FK_B26681ED936B2FA');
        $this->addSql('ALTER TABLE log_securite DROP CONSTRAINT FK_BFC94251FB88E14F');
        $this->addSql('ALTER TABLE ticket_design DROP CONSTRAINT FK_B70D30FBFD02F13');
        $this->addSql('DROP TABLE app_setting');
        $this->addSql('DROP TABLE billet');
        $this->addSql('DROP TABLE commande');
        $this->addSql('DROP TABLE commande_ligne');
        $this->addSql('DROP TABLE evenement');
        $this->addSql('DROP TABLE log_securite');
        $this->addSql('DROP TABLE ticket_design');
        $this->addSql('DROP TABLE utilisateur');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
