security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: auth.login
                check_path: auth.login
                default_target_path: portefeuille.index
                username_parameter: email
                password_parameter: password
            logout:
                path: auth.logout
                target: accueil

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/organisateur, roles: ROLE_ORGANISATEUR }
        - { path: ^/connexion, roles: PUBLIC_ACCESS }
        - { path: ^/inscription, roles: PUBLIC_ACCESS }
        - { path: ^/evenements, roles: PUBLIC_ACCESS }
        - { path: ^/panier, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/portefeuille, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/achat, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/$, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            App\Entity\User:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
