# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource: 
        path: ../src/Controller # routing.controllers
        namespace: App\Controller
    type: attribute

# Routes manuelles pour BalanceController
balance_index:
    path: /balance
    controller: App\Controller\BalanceController::index
    methods: [GET]

balance_check_payments:
    path: /balance/check-payments
    controller: App\Controller\BalanceController::checkPayments
    methods: [POST]

balance_api:
    path: /balance/api/balance
    controller: App\Controller\BalanceController::apiBalance
    methods: [GET]
